'use strict'

const test = require('tape')
const fs = require('fs-extra')
const { resolve } = require('path')
const convert = require('../src/convert.js')

const testStr = `"
" sandbox v1.0.0
" testing estilo
" https://github.com/jacoborus/estilo#readme
" author: Jacobo
" license: MIT
" background: dark
"
" This file was generated by Estilo
" https://github.com/jacoborus/estilo

let colors_name="sandbox"
hi clear
if exists("syntax_on")
  syntax reset
endif
if has("gui_running")
  set background=dark
endif

hi ColorColumn guifg=#bbddff ctermfg=153 guibg=#bbddff ctermbg=153 gui=bold,italic,reverse,underline cterm=bold,italic,reverse,underline
hi Comment guifg=#bbddff ctermfg=153 guibg=#bbddff ctermbg=153 gui=bold,italic,reverse,underline cterm=bold,italic,reverse,underline
hi jsonPadding guifg=#bbddff ctermfg=153 guibg=#bbddff ctermbg=153 gui=bold,italic,reverse,underline cterm=bold,italic,reverse,underline\n`

test('build', t => {
  fs.removeSync('./test/sandbox/colors')
  convert(resolve('./test/sandbox'))
  const str = fs.readFileSync('./test/sandbox/colors/sandbox.vim', 'utf-8')
  t.is(str, testStr)
  fs.unlink('./test/sandbox/colors/sandbox.vim', () => {
    t.end()
  })
})
