'use strict'


const watermark = `"
" This file was generated by vim-styler
" https://github.com/jacoborus/vim-styler\n\n`

function getFirst (info) {
  let out = `"\n" ${info.scheme}`
  if (info.version) {
    out += ' v' + info.version
  }
  out += '\n'
  return out
}

const props = new Set(['description', 'url'])
const defs = new Set(['author', 'license', 'background'])

module.exports = function (info) {
  let out = getFirst(info)
  props.forEach(p => {
    if (p in info) {
      out += `" ${info[p]}\n`
    }
  })
  defs.forEach(d => {
    if (d in info) {
      out += `" ${d}: ${info[d]}\n`
    }
  })
  out += watermark
  return out
}
