'use strict'


function getVimCode (info) {
  return `let g:colors_name="${info.name}"
hi clear
if exists("syntax_on")
  syntax reset
endif
if has("gui_running")
  set background=${info.background}
endif\n\n`
}

const watermark = `"
" This file was generated by Estilo
" https://github.com/jacoborus/estilo\n\n`

function getFirst (info) {
  let out = `"\n" ${info.name}`
  if (info.version) {
    out += ' v' + info.version
  }
  out += '\n'
  return out
}

const props = new Set(['description', 'homepage'])
const defs = new Set(['author', 'license', 'background'])

module.exports = function (info) {
  let out = getFirst(info)
  props.forEach(p => {
    if (p in info) {
      out += `" ${info[p]}\n`
    }
  })
  defs.forEach(d => {
    if (d in info) {
      out += `" ${d}: ${info[d]}\n`
    }
  })
  out += watermark
  out += getVimCode(info)
  return out
}
