'use strict'


function getVimCode (theme) {
  return `let g:colors_name="${theme.name}"
hi clear
if exists("syntax_on")
  syntax reset
endif
if has("gui_running")
  set background=${theme.background}
endif\n\n`
}

const watermark = `"
" This file was generated by Estilo
" https://github.com/jacoborus/estilo\n\n`

function getFirst (info, theme) {
  let out = `"\n" ${theme.name}`
  if (info.version) {
    out += ` v${info.version}`
  }
  out += '\n'
  return out
}

const props = new Set(['description', 'homepage'])
const defs = new Set(['author', 'license'])

module.exports = function (info, theme) {
  let out = getFirst(info, theme)
  props.forEach(p => {
    if (p in info) {
      out += `" ${info[p]}\n`
    }
  })
  defs.forEach(d => {
    if (d in info) {
      out += `" ${d}: ${info[d]}\n`
    }
  })
  out += watermark
  out += getVimCode(theme)
  return out
}
