export default function (theme, pkg, date: string, c, estiloVersion): string {
  return `
" ============================================================
" ${theme.name}
" ${theme.description}
" URL:${pkg.url}
" Author: ${pkg.author}
" License: ${pkg.license}
" Last Change: ${date}
" ============================================================

let g:airline#themes#${theme.name}#palette = {}

let s:normal1 = [ "${c.normal1[0][0]}", "${c.normal1[1][0]}", ${c.normal1[0][1]}, ${c.normal1[1][1]} ]
let s:normal2 = [ "${c.normal2[0][0]}", "${c.normal2[1][0]}", ${c.normal2[0][1]}, ${c.normal2[1][1]} ]
let s:normal3 = [ "${c.normal3[0][0]}", "${c.normal3[1][0]}", ${c.normal3[0][1]}, ${c.normal3[1][1]} ]
let g:airline#themes#${c.theme.name}#palette.normal = airline#themes#generate_color_map(s:normal1, s:normal2, s:normal3)

let s:insert1 = [ "${c.insert1[0][0]}", "${c.insert1[1][0]}", ${c.insert1[0][1]}, ${c.insert1[1][1]} ]
let s:insert2 = [ "${c.insert2[0][0]}", "${c.insert2[1][0]}", ${c.insert2[0][1]}, ${c.insert2[1][1]} ]
let s:insert3 = [ "${c.insert3[0][0]}", "${c.insert3[1][0]}", ${c.insert3[0][1]}, ${c.insert3[1][1]} ]
let g:airline#themes#${c.theme.name}#palette.insert = airline#themes#generate_color_map(s:insert1, s:insert2, s:insert3)

let s:replace1 = [ "${c.replace1[0][0]}", "${c.replace1[1][0]}", ${c.replace1[0][1]}, ${c.replace1[1][1]} ]
let s:replace2 = [ "${c.replace2[0][0]}", "${c.replace2[1][0]}", ${c.replace2[0][1]}, ${c.replace2[1][1]} ]
let s:replace3 = [ "${c.replace3[0][0]}", "${c.replace3[1][0]}", ${c.replace3[0][1]}, ${c.replace3[1][1]} ]
let g:airline#themes#${c.theme.name}#palette.replace = airline#themes#generate_color_map(s:replace1, s:replace2, s:replace3)

let s:visual1 = [ "${c.visual1[0][0]}", "${c.visual1[1][0]}", ${c.visual1[0][1]}, ${c.visual1[1][1]} ]
let s:visual2 = [ "${c.visual2[0][0]}", "${c.visual2[1][0]}", ${c.visual2[0][1]}, ${c.visual2[1][1]} ]
let s:visual3 = [ "${c.visual3[0][0]}", "${c.visual3[1][0]}", ${c.visual3[0][1]}, ${c.visual3[1][1]} ]
let g:airline#themes#${c.theme.name}#palette.visual = airline#themes#generate_color_map(s:visual1, s:visual2, s:visual3)

let s:inactive1 = [ "${c.inactive1[0][0]}", "${c.inactive1[1][0]}", ${c.inactive1[0][1]}, ${c.inactive1[1][1]} ]
let s:inactive2 = [ "${c.inactive2[0][0]}", "${c.inactive2[1][0]}", ${c.inactive2[0][1]}, ${c.inactive2[1][1]} ]
let s:inactive3 = [ "${c.inactive3[0][0]}", "${c.inactive3[1][0]}", ${c.inactive3[0][1]}, ${c.inactive3[1][1]} ]
let g:airline#themes#${theme.name}#palette.inactive = airline#themes#generate_color_map(s:inactive1, s:inactive2, s:inactive3)

${c.ctrlp1 ? `
if !get(g:, 'loaded_ctrlp', 0)
  finish
endif

let s:CP1 = [ "${c.ctrlp1[0][0]}", "${c.ctrlp1[1][0]}", ${c.ctrlp1[0][1]}, ${c.ctrlp1[1][1]} ]
let s:CP2 = [ "${c.ctrlp2[0][0]}", "${c.ctrlp2[1][0]}", ${c.ctrlp2[0][1]}, ${c.ctrlp2[1][1]} ]
let s:CP3 = [ "${c.ctrlp3[0][0]}", "${c.ctrlp3[1][0]}", ${c.ctrlp3[0][1]}, ${c.ctrlp3[1][1]} ]

let g:airline#themes#${theme.name}#palette.ctrlp = airline#extensions#ctrlp#generate_color_map(s:CP1, s:CP2, s:CP3)
` : ''}

" Generated by Estilo ${estiloVersion} (https://github.com/jacoborus/estilo)
`
}
