export function renderLightline (theme, pkg, c, estiloVersion): string {
  return `" ============================================================
" ${theme.name}
" ${theme.description}
" URL: ${pkg.url}
" Author: ${pkg.author}
" License: ${pkg.license}
" ============================================================

let s:p = {"normal": {}, "inactive": {}, "insert": {}, "replace": {}, "visual": {}, "tabline": {} }

let s:p.normal.left = [[["${c.normal1[0][0]}", ${c.normal1[0][1]}], ["${c.normal1[1][0]}", ${c.normal1[1][1]}]], [["${c.normal2[0][0]}", ${c.normal2[0][1]}], ["${c.normal2[1][0]}", ${c.normal2[1][1]}]]]
let s:p.normal.middle = [[["${c.normal3[0][0]}", ${c.normal3[0][1]}], ["${c.normal3[1][0]}", ${c.normal3[1][1]}]]]
let s:p.normal.right = [[["${c.normal4[0][0]}", ${c.normal4[0][1]}], ["${c.normal4[1][0]}", ${c.normal4[1][1]}]], [["${c.normal5[0][0]}", ${c.normal5[0][1]}], ["${c.normal5[1][0]}", ${c.normal5[1][1]}]]]
let s:p.normal.error = [[["${c.normalError[0][0]}", ${c.normalError[0][1]}], ["${c.normalError[1][0]}", ${c.normalError[1][1]}]]]
let s:p.normal.warning = [[["${c.normalWarning[0][0]}", ${c.normalWarning[0][1]}], ["${c.normalWarning[1][0]}", ${c.normalWarning[1][1]}]]]

let s:p.inactive.left = [[["${c.inactive1[0][0]}", ${c.inactive1[0][1]}], ["${c.inactive1[1][0]}", ${c.inactive1[1][1]}]], [["${c.inactive2[0][0]}", ${c.inactive2[0][1]}], ["${c.inactive2[1][0]}", ${c.inactive2[1][1]}]]]
let s:p.inactive.middle = [[["${c.inactive3[0][0]}", ${c.inactive3[0][1]}], ["${c.inactive3[1][0]}", ${c.inactive3[1][1]}]]]
let s:p.inactive.right = [[["${c.inactive4[0][0]}", ${c.inactive4[0][1]}], ["${c.inactive4[1][0]}", ${c.inactive4[1][1]}]], [["${c.inactive5[0][0]}", ${c.inactive5[0][1]}], ["${c.inactive5[1][0]}", ${c.inactive5[1][1]}]]]

let s:p.insert.left = [[["${c.insert1[0][0]}", ${c.insert1[0][1]}], ["${c.insert1[1][0]}", ${c.insert1[1][1]}]], [["${c.insert2[0][0]}", ${c.insert2[0][1]}], ["${c.insert2[1][0]}", ${c.insert2[1][1]}]]]
let s:p.insert.middle = [[["${c.insert3[0][0]}", ${c.insert3[0][1]}], ["${c.insert3[1][0]}", ${c.insert3[1][1]}]]]
let s:p.insert.right = [[["${c.insert4[0][0]}", ${c.insert4[0][1]}], ["${c.insert4[1][0]}", ${c.insert4[1][1]}]], [["${c.insert5[0][0]}", ${c.insert5[0][1]}], ["${c.insert5[1][0]}", ${c.insert5[1][1]}]]]

let s:p.replace.left = [[["${c.replace1[0][0]}", ${c.replace1[0][1]}], ["${c.replace1[1][0]}", ${c.replace1[1][1]}]], [["${c.replace2[0][0]}", ${c.replace2[0][1]}], ["${c.replace2[1][0]}", ${c.replace2[1][1]}]]]
let s:p.replace.middle = [[["${c.replace3[0][0]}", ${c.replace3[0][1]}], ["${c.replace3[1][0]}", ${c.replace3[1][1]}]]]
let s:p.replace.right = [[["${c.replace4[0][0]}", ${c.replace4[0][1]}], ["${c.replace4[1][0]}", ${c.replace4[1][1]}]], [["${c.replace5[0][0]}", ${c.replace5[0][1]}], ["${c.replace5[1][0]}", ${c.replace5[1][1]}]]]

let s:p.visual.left = [[["${c.visual1[0][0]}", ${c.visual1[0][1]}], ["${c.visual1[1][0]}", ${c.visual1[1][1]}]], [["${c.visual2[0][0]}", ${c.visual2[0][1]}], ["${c.visual2[1][0]}", ${c.visual2[1][1]}]]]
let s:p.visual.middle = [[["${c.visual3[0][0]}", ${c.visual3[0][1]}], ["${c.visual3[1][0]}", ${c.visual3[1][1]}]]]
let s:p.visual.right = [[["${c.visual4[0][0]}", ${c.visual4[0][1]}], ["${c.visual4[1][0]}", ${c.visual4[1][1]}]], [["${c.visual5[0][0]}", ${c.visual5[0][1]}], ["${c.visual5[1][0]}", ${c.visual5[1][1]}]]]

let s:p.tabline.left = [[["${c.tablineLeft[0][0]}", ${c.tablineLeft[0][1]}], ["${c.tablineLeft[1][0]}", ${c.tablineLeft[1][1]}]]]
let s:p.tabline.tabsel = [[["${c.tablineSelected[0][0]}", ${c.tablineSelected[0][1]}], ["${c.tablineSelected[1][0]}", ${c.tablineSelected[1][1]}]]]
let s:p.tabline.middle = [[["${c.tablineMiddle[0][0]}", ${c.tablineMiddle[0][1]}], ["${c.tablineMiddle[1][0]}", ${c.tablineMiddle[1][1]}]]]
let s:p.tabline.right = [[["${c.tablineRight[0][0]}", ${c.tablineRight[0][1]}], ["${c.tablineRight[1][0]}", ${c.tablineRight[1][1]}]]]

let g:lightline#colorscheme#${theme.name}#palette = lightline#colorscheme#flatten(s:p)

" Generated by Estilo ${estiloVersion} (https://github.com/jacoborus/estilo)
`
}
